# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionCli < Formula
  desc "Notion CLI for exporting and managing Notion content"
  homepage "https://github.com/inforix/notion-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inforix/notion-cli/releases/download/v0.1.0/notion_0.1.0_darwin_amd64.tar.gz"
      sha256 "fef65e68f4adda02e272dc96eed428fde89a321796c65733d0bd22eb3d7edc27"

      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inforix/notion-cli/releases/download/v0.1.0/notion_0.1.0_darwin_arm64.tar.gz"
      sha256 "58e27bfa982cff864f20d09112e7d6a01911973e93429db2c1148e0fe42d44b4"

      define_method(:install) do
        bin.install "notion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inforix/notion-cli/releases/download/v0.1.0/notion_0.1.0_linux_amd64.tar.gz"
      sha256 "2e730aec71831544064260f4a35a190687d28fbad3eadcd363c76091ec7fcbf6"
      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inforix/notion-cli/releases/download/v0.1.0/notion_0.1.0_linux_arm64.tar.gz"
      sha256 "aa28f382d2a416260b75c496038ecd26e2f399ed2f5e6251e2c9d58bccfc7b57"
      define_method(:install) do
        bin.install "notion"
      end
    end
  end
end
