# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionCli < Formula
  desc "Notion CLI for exporting and managing Notion content"
  homepage "https://github.com/inforix/notion-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inforix/notion-cli/releases/download/v0.2.0/notion_0.2.0_darwin_amd64.tar.gz"
      sha256 "913e0823b872bbbab415d4bdb104c0190fab991c0b45d59d16f2eed38e2562a9"

      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inforix/notion-cli/releases/download/v0.2.0/notion_0.2.0_darwin_arm64.tar.gz"
      sha256 "40192de90a0234502f1e41b5622308f7e4c90562cba68d1de93516094de7fcda"

      define_method(:install) do
        bin.install "notion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inforix/notion-cli/releases/download/v0.2.0/notion_0.2.0_linux_amd64.tar.gz"
      sha256 "26d7d2d9e6cf098ec5afa23ca4a5e255d4a05d184ef6500d5adc12c872091abc"
      define_method(:install) do
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inforix/notion-cli/releases/download/v0.2.0/notion_0.2.0_linux_arm64.tar.gz"
      sha256 "c1e65574d13d20a67847ca9281ceea7a54f68bf37a82f6ba1a58c2c8bcf0e8b9"
      define_method(:install) do
        bin.install "notion"
      end
    end
  end
end
